testPlatform: "Desktop" # Valid values : Desktop , Mobile
browser: "CHROME" # FIREFOX,CHROME
environment: "local" #Valid values : local , remote
mobileOS: "android" #Valid values : ios , android
applicationUrl: "https://vickynov13.github.io"
driverpath:
  chrome: "path/to/chromedriver"
